pretrained_model_path: "./checkpoints/stable-diffusion-v1-4"
output_dir: "./outputs/10_classes_6000_epochs"

train_data:
  video_path: "data/panda01.mp4"
  prompt: "a panda is eatting bamboo"
  n_sample_frames: 6
  width: 512
  height: 288
  sample_start_idx: 0
  sample_frame_rate: 2

validation_data:
  prompts:
    - "a cat is sitting on the ground"
    - "an airplane in the sky"
    - "a person is dancing"
  video_length: 6
  width: 512
  height:  288
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: False
  num_inv_steps: 50

learning_rate: 3e-5
train_batch_size: 10
max_train_steps: 500
checkpointing_steps: 1000
validation_steps: 100
trainable_modules:
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
