#pretrained_model_path: "Zhoutianyi/huggingface/stable-diffusion-v1-4"
pretrained_model_path: "/home/drink/huggingface/stable-diffusion-v1-4"
output_dir: "./outputs/40_classes_200_epoch/"

train_data:
  video_path: "/home/drink/SEED-DV/Video_Mp4/Block1/163.mp4"
  prompt: "a turtle swimming in the water"
  n_sample_frames: 6
  width: 512
  height: 288
  sample_start_idx: 0
  sample_frame_rate: 2

validation_data:
  prompts:
    - "a cat is sleeping on the sofa"
    - "an airplane in the sky"
    - "a person is dancing"
  video_length: 6
  width: 512
  height:  288
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: False
  num_inv_steps: 50

learning_rate: 3e-5
train_batch_size: 4 #10
max_train_steps: 200 #200
checkpointing_steps: 1000 #1000
validation_steps: 100 #100
trainable_modules:
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
